name: "App token extractor"
description: "Return the github app token"
inputs:
  app_id:
    description: "App id"
    required: true
  private_key:
    description: "App private key"
    required: true
runs:
  using: docker
  image: "Dockerfile"
  args:
    - ${{ inputs.private_key }}
    - ${{ inputs.app_id }}