version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/server"
    groups:
       server-dependencies:
          patterns:
            - "*"
    schedule:
      interval: "daily"
      time: "09:00"
  - package-ecosystem: "npm"
    directories:
      - "/playwright"
    ignore:
    - dependency-name: 'eslint'
    groups:
      playwright-dependencies:
        patterns:
          - "*"
    schedule:
      interval: "daily"
      time: "09:00"
  - package-ecosystem: "npm"
    directories:
      - "/web"
    ignore:
    - dependency-name: 'eslint'
    groups:
      web-dependencies:
        patterns:
          - "*"
    schedule:
      interval: "daily"
      time: "09:00"
  - package-ecosystem: "npm"
    directories:
      - "/scripts"
    groups:
      scripts-dependencies:
        patterns:
          - "*"
    schedule:
      interval: "daily"
      time: "09:00"

