version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/server"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

