version: "3"
services:
  server:
    image: amazoncorretto:17-alpine3.17
    working_dir: /ludos
    command: server/gradlew bootJar -p server
    volumes:
      - ./web:/ludos/web
      - ./server:/ludos/server
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - DB_URL=jdbc:postgresql://host.docker.internal:5432/ludos 
    ports:
      - "8080:8080"
