ARG PLAYWRIGHT_VERSION
FROM mcr.microsoft.com/playwright:v${PLAYWRIGHT_VERSION}-noble

ADD playwright/package.json playwright/package.json
ADD playwright/package-lock.json playwright/package-lock.json

COPY playwright/ /playwright/
RUN cd playwright && npm ci && cd ..

COPY web/ /web/
RUN cd web && npm ci && cd ..

ADD scripts scripts

ADD playwright-dockerfile-entrypoint.sh playwright-dockerfile-entrypoint.sh

COPY server/src/main/resources/fixtures /server/src/main/resources/fixtures
COPY server/src/main/resources/backup_data /server/src/main/resources/backup_data

ENTRYPOINT ["./playwright-dockerfile-entrypoint.sh"]
