name: Code check
description: Run eslint and prettier on project TypeScript files

runs:
  using: composite
  steps:
    - name: ci web
      working-directory: ./web
      shell: bash
      run: npm ci
    - name: Lint web
      working-directory: ./web
      shell: bash
      run: npm run lint
    - name: ci localizations
      working-directory: ./scripts
      shell: bash
      run: npm ci
    - name: Lint localizations
      working-directory: ./scripts
      shell: bash
      run: npm run lint
    - name: ci playwright
      working-directory: ./playwright
      shell: bash
      run: npm ci
    - name: Lint playwright
      working-directory: ./playwright
      shell: bash
      run: npm run lint
