name: Code check
description: Run eslint and prettier on project TypeScript files

runs:
  using: composite
  steps:
    - name: Lint web
      working-directory: ./web
      shell: bash
      run: npm run lint
    - name: Lint playwright
      working-directory: ./playwright
      shell: bash
      run: npm run lint
