FROM node:22-bookworm@sha256:978e96850e9e828eda68610829a01f70317e353dcd3d146f2fff93880f13dcb4

RUN curl \
    "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_arm64/session-manager-plugin.deb" \
    -o "/tmp/session-manager-plugin.deb"
RUN dpkg -i /tmp/session-manager-plugin.deb

RUN apt-get update && apt-get install -y awscli bash socat daemonize netcat-traditional

COPY . /app
WORKDIR /app

CMD ["/app/entrypoint.sh"]
