FROM node:24-bookworm@sha256:da4221677e02b54ef6335adfa447578d512ad14f251024fb92ea433c2c102760

RUN curl \
    "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_arm64/session-manager-plugin.deb" \
    -o "/tmp/session-manager-plugin.deb"
RUN dpkg -i /tmp/session-manager-plugin.deb

RUN apt-get update && apt-get install -y awscli bash socat daemonize netcat-traditional

COPY . /app
WORKDIR /app

CMD ["/app/entrypoint.sh"]
