name: Push image
description: Upload built image to AWS ECR

runs:
  using: composite
  steps:
    - name: Configure utility AWS credentials
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
      with:
        role-to-assume: arn:aws:iam::505953557276:role/ludos-gh-actions-ecr-push-role
        aws-region: eu-west-1

    - name: 05-push-image.sh
      working-directory: ./
      shell: bash
      run: ./deploy-scripts/05-push-image.sh