name: Push image
description: Upload built image to AWS ECR
inputs:
  env:
    description: 'Environment for deployment'
    required: true
  username:
    description: ghcr.io username
    required: true
  password:
    description: ghcr.io password
    required: true


runs:
  using: composite
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.2.0
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Configure utility AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::505953557276:role/ludos-gh-actions-ecr-push-role
        aws-region: eu-west-1

    - name: 05-push-image.sh
      working-directory: ./
      shell: bash
      run: ./deploy-scripts/05-push-image-${{ inputs.env }}.sh