FROM node:23-alpine3.20

WORKDIR /app

COPY ./package-lock.json .
COPY ./package.json .

RUN npm ci

COPY ./index.ts .
COPY ./tsconfig.json .
RUN npx tsc --noEmit
ENTRYPOINT ["npx", "tsx", "index.ts"]

