FROM node:22-alpine3.20@sha256:a6ad3754456c829b6bb90f7e69420cc0e8905c515457bab929f20bb67fef0167

WORKDIR /app

COPY ./package-lock.json .
COPY ./package.json .

RUN npm ci

COPY ./index.ts .
COPY ./tsconfig.json .
RUN npx tsc --noEmit
ENTRYPOINT ["npx", "tsx", "index.ts"]

