FROM node:22-alpine3.20@sha256:c8576ba7d35431f265e7f5b33085f7af5246ea37b947528f6776e73ad3ec9233

WORKDIR /app

COPY ./package-lock.json .
COPY ./package.json .

RUN npm ci

COPY ./index.ts .
COPY ./tsconfig.json .
RUN npx tsc --noEmit
ENTRYPOINT ["npx", "tsx", "index.ts"]

