name: Start service
description: Starts up the frontend and backend
inputs:
  ludos-profiles:
    description: Ludos profiles as comma separated list
    required: true
  ludos-palvelukayttaja-username:
    description: Ludos-palvelukäyttäjän käyttäjätunnus
    required: true
  ludos-palvelukayttaja-password:
    description: Ludos-palvelukäyttäjän salasana
    required: true
runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
      with:
        role-to-assume: arn:aws:iam::782034763554:role/ludos-github-actions-role-untuva
        aws-region: eu-west-1
    - name: Start service
      shell: bash
      env:
        LUDOS_PALVELUKAYTTAJA_USERNAME: ${{ inputs.ludos-palvelukayttaja-username }}
        LUDOS_PALVELUKAYTTAJA_PASSWORD: ${{ inputs.ludos-palvelukayttaja-password }}
      run: LUDOS_PROFILES="${{ inputs.ludos-profiles }}" docker-build/run.sh 2>&1 | tee service.log &
    - name: Wait until service is online
      shell: bash
      run: timeout 120 bash -c "while true; do curl -sS -o /dev/null http://localhost:8080/ && break; sleep 2; done; echo 'Service responding, continuing'"
