name: Vitest Unit Tests
description: Run frontend unit tests
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: v20.11.0
        cache: npm 
    - name: npm install
      working-directory: ./web
      shell: bash
      run: npm ci 
    - name: run unit tests
      working-directory: ./web
      shell: bash
      run: npm run test
