name: Build status
description: Send build status to Jatkuvat Radiator
inputs:
  api_key:
    description: Radiator API key for Ludos
    required: true
  task:
    description: Task name ('build-image', 'deploy-untuva', 'deploy-qa', 'deploy-prod')
    required: true
  status:
    description: Build status ('unknown', 'success', 'failure', 'cancelled', 'inProgress')
    required: true

runs:
  using: composite
  steps:
    - name: Send in-progress status to radiator
      shell: bash
      working-directory: ./
      run: |
        body=$(jq -n \
          --arg status "${{ inputs.status }}" \
          --arg commitHeader "$(git log -1 --pretty=%s)" \
          --arg committer "$(git log -1 --pretty=%an)" \
          --arg commitHash "${{ github.sha }}" \
          --arg deployer "${{ github.actor }}" \
          --arg runId "${{ github.run_id }}" \
          '$ARGS.named')
        curl \
          -H "AUTH_TOKEN: ${{ inputs.api_key }}" \
          -H "Content-Type: application/json" \
          -X PUT \
          https://radiator.continuous-services.services/api/v2/buildstatus/ludos/${{ inputs.task }} \
          -d "$body"
