name: Build status
description: Send build status to Jatkuvat Radiator
inputs:
  api_key:
    description: Radiator API key for Ludos
    required: true
  task:
    description: Task name ('build-image', 'deploy-untuva', 'deploy-qa', 'deploy-prod')
    required: true
  status:
    description: Build status ('unknown', 'success', 'failure', 'cancelled', 'inProgress')
    required: true

runs:
  using: composite
  steps:
    - name: Send in-progress status to radiator
      shell: bash
      working-directory: ./
      run: |
        curl \
          -H "AUTH_TOKEN: ${{ inputs.api_key }}" \
          -H "Content-Type: application/json" \
          -X PUT \
          https://radiator.continuous-services.services/api/v2/buildstatus/ludos/${{ inputs.task }} \
          -d "{\"status\": \"${{ inputs.status }}\"}"
