name: Localization check
description: Localization checks

inputs:
  ludos-environment:
    description: Ludos environment to check against
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
      with:
        node-version: 22.21.0
        cache: npm
    - name: npm install
      working-directory: ./scripts
      shell: bash
      run: npm ci
    - name: Check for missing keys in untuva
      working-directory: ./scripts
      shell: bash
      run: npm run localizations list-missing --error-if-missing --github-actions ${{ inputs.ludos-environment }}
