name: Localization check
description: Localization checks

inputs:
  ludos-environment:
    description: Ludos environment to check against
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version: 24.14.0
        cache: npm
    - name: npm install
      working-directory: ./scripts
      shell: bash
      run: npm ci
    - name: Check for missing keys in untuva
      working-directory: ./scripts
      shell: bash
      run: npm run localizations list-missing --error-if-missing --github-actions ${{ inputs.ludos-environment }}
