name: Localization check
description: Localization checks

inputs:
  ludos-environment:
    description: Ludos environment to check against
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        node-version: 22.20.0
        cache: npm
    - name: npm install
      working-directory: ./scripts
      shell: bash
      run: npm ci
    - name: Check for missing keys in untuva
      working-directory: ./scripts
      shell: bash
      run: npm run localizations list-missing --error-if-missing --github-actions ${{ inputs.ludos-environment }}
