name: Localization check
description: Localization checks

inputs:
  ludos-environment:
    description: Ludos environment to check against
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: npm
    - name: npm install
      shell: bash
      run: npm ci
    - name: Check for missing keys in untuva
      working-directory: ./scripts
      shell: bash
      run: npm run localizations list-missing --error-if-missing --github-actions ${{ inputs.ludos-environment }}
