name: Start frontend and backend
description: Starts up the frontend and backend
runs:
  using: composite
  steps:
    - name: Build frontend and backend
      shell: bash
      run: cd server && ./gradlew build
    - name: Start backend
      shell: bash
      run: cd server && ./gradlew bootRun --args='--spring.profiles.active=local' 2>&1 | tee bootRun.log &
