name: Playwright Tests
description: Run playwright tests
inputs:
  ludos-profiles:
    description: Ludos profiles as comma separated list
    required: true
  projects:
    description: The playwright projects to run as a space separated list
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: yarn
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: zulu
    - name: 'Start database'
      shell: bash
      run: docker compose up -d
    - uses: actions/download-artifact@v3
      with:
        name: jar
        path: server/build/libs
    - name: '🔨 Start frontend and backend'
      uses: ./.github/actions/start_service
      with:
        ludos-profiles: ${{ inputs.ludos-profiles }}
    - name: yarn install
      shell: bash
      run: yarn install --frozen-lockfile
    - name: 'Get playwright version'
      id: playwright_version
      shell: bash
      run: echo "playwright_version=$(npx playwright --version | cut -d' ' -f2)" >> $GITHUB_OUTPUT
    - name: Cache Playwright browser
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright_version.outputs.playwright_version }}
        restore-keys: |
          ${{ runner.os }}-playwright-
    - name: Install Playwright Browsers
      shell: bash
      run: npx playwright install --with-deps chromium
    - name: Run Playwright tests
      shell: bash
      run: yarn playwright --project ${{ inputs.projects }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-debug-artifacts
        path: |
          playwright/test-results/
          service.log
        retention-days: 30
