name: Playwright Tests
description: Run playwright tests
inputs:
  ludos-profiles:
    description: Ludos profiles as comma separated list
    required: true
  browsers:
    description: The browsers to install
    required: false
    default: chromium
  testikayttaja-yllapitaja-username:
    description: Ylläpitäjä-testikäyttäjän käyttäjätunnus
    default: "username"
    required: false
  testikayttaja-yllapitaja-password:
    description: Ylläpitäjä-testikäyttäjän salasana
    default: "password"
    required: false
  ludos-palvelukayttaja-username:
    description: Ludos-palvelukäyttäjän käyttäjätunnus
    required: true
  ludos-palvelukayttaja-password:
    description: Ludos-palvelukäyttäjän salasana
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: yarn
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: zulu
    - name: 'Start database'
      shell: bash
      run: docker compose up -d
    - uses: actions/download-artifact@v3
      with:
        name: jar
        path: server/build/libs
    - name: '🔨 Start frontend and backend'
      uses: ./.github/actions/start_service
      with:
        ludos-profiles: ${{ inputs.ludos-profiles }}
        ludos-palvelukayttaja-username: ${{ inputs.ludos-palvelukayttaja-username }}
        ludos-palvelukayttaja-password: ${{ inputs.ludos-palvelukayttaja-password }}
    - name: yarn install
      shell: bash
      run: yarn install --frozen-lockfile
    - name: 'Get playwright version'
      id: playwright_version
      shell: bash
      run: echo "playwright_version=$(npx playwright --version | cut -d' ' -f2)" >> $GITHUB_OUTPUT
    - name: List Playwright Ubuntu dependencies
      id: playwright-ubuntu-deps
      shell: bash
      run: echo playwright-ubuntu-deps=$(npx playwright install-deps --dry-run ${{ inputs.browsers }} 2>&1 | grep -Po '(?<=no-install-recommends ).*(?=")') >> $GITHUB_OUTPUT
    - name: Cache Playwright browser
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright_version.outputs.playwright_version }}
        restore-keys: |
          ${{ runner.os }}-playwright-
    - uses: tecolicom/actions-use-apt-tools@v1
      with:
        tools: ${{ steps.playwright-ubuntu-deps.outputs.playwright-ubuntu-deps }}
    - name: Install Playwright Browsers
      shell: bash
      run: npx playwright install ${{ inputs.browsers }}
    - name: Run Playwright tests
      shell: bash
      env:
        TESTIKAYTTAJA_YLLAPITAJA_USERNAME: ${{ inputs.testikayttaja-yllapitaja-username }}
        TESTIKAYTTAJA_YLLAPITAJA_PASSWORD: ${{ inputs.testikayttaja-yllapitaja-password }}
      run: yarn playwright:ci
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-debug-artifacts
        path: |
          playwright/test-results/
          service.log
        retention-days: 30
