name: Playwright Tests
description: Run playwright tests

runs:
  using: composite
  steps:
    - name: 'Start database'
      shell: bash
      run: docker compose up -d
    - name: '🔨 Start frontend and backend'
      uses: ./.github/actions/start_service
    - name: Cache Playwright browser
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('./playwright/playwright.config.ts') }}
        restore-keys: |
          ${{ runner.os }}-playwright-
    - name: yarn install
      shell: bash
      run: yarn install --frozen-lockfile
    - name: Install Playwright Browsers
      shell: bash
      run: npx playwright install --with-deps chromium
    - name: Run Playwright tests
      shell: bash
      run: yarn playwright
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: |
          playwright/playwright-report/
          service.log
        retention-days: 30
