name: Playwright Tests
description: Run playwright tests

runs:
  using: composite
  steps:
    - name: 'Start database'
      shell: bash
      run: docker compose up -d
    - name: '🔨 Start frontend and backend'
      uses: ./.github/actions/start_service
    - name: yarn install
      shell: bash
      run: yarn install --frozen-lockfile
    - name: 'Get playwright version'
      id: playwright_version
      shell: bash
      run: echo "playwright_version=$(npx playwright --version | cut -d' ' -f2)" >> $GITHUB_OUTPUT
    - name: Cache Playwright browser
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright_version.outputs.playwright_version }}
        restore-keys: |
          ${{ runner.os }}-playwright-
    - name: Install Playwright Browsers
      shell: bash
      run: npx playwright install --with-deps chromium
    - name: Run Playwright tests
      shell: bash
      run: yarn playwright
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: |
          playwright/playwright-report/
          service.log
        retention-days: 30
