name: dependabot-pagerduty-alert

on:
  pull_request:
    types: [opened]

jobs:
  create-alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: 'main'

      - name: Send PagerDuty alert if PR created by dependabot
        if: github.base_ref == 'main' && github.actor == 'dependabot[bot]'
        run: |
          ./scripts/post-pagerduty-alert.sh trigger ludos-github-action-dependabot "Dependabot created a new PR to ${{ github.repository }}"
        env:
          PAGERDUTY_ROUTING_KEY: ${{ secrets.PAGERDUTY_ROUTING_KEY }}
