name: Scheduled Renovate Execution
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0/20 * * * *'

concurrency: renovate

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: ./.github/actions/app-token-exporter
        id: app-token
        with:
          private_key: ${{ secrets.PRIVATE_KEY }}
          app_id: ${{ secrets.APP_ID }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@3064367f740a1a91cca218698a63902689cce200 # v46.1.20
        with:
          configurationFile: .github/renovate.json
          token: ${{ steps.app-token.outputs.token }}
          renovate-version: 42-full
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_REPOSITORIES: 'Opetushallitus/ludos'
          RENOVATE_AUTODISCOVER_FILTER: 'Opetushallitus/ludos'
          RENOVATE_ALLOWED_COMMANDS: 'cd server && ./gradlew dependencies --write-locks'
